"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
type Persona={id:number;nombre:string;codigo:string};
type Hilo={id:number;titulo:string;descripcion:string;tipo:string;modulo:string;ruta?:string|null;prioridad:string;estado:string;responsable_id?:number|null;created_at:string;updated_at:string;fecha_resolucion?:string|null;creador?:Persona;responsable?:Persona|null;resuelto?:Persona|null};
type Comentario={id:number;contenido:string;tipo:string;created_at:string;autor?:Persona};
export default function DetalleBitacoraPage(){const {id}=useParams<{id:string}>();const [hilo,setHilo]=useState<Hilo|null>(null),[comentarios,setComentarios]=useState<Comentario[]>([]),[responsables,setResponsables]=useState<Persona[]>([]),[error,setError]=useState(""),[guardando,setGuardando]=useState(false);
const cargar=useCallback(async()=>{try{const u=JSON.parse(localStorage.getItem("user")||"{}");const r=await fetch(`/api/bitacora/${id}`,{headers:{"x-user-codigo":u.codigo||""},cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);setHilo(j.hilo);setComentarios(j.comentarios||[]);setResponsables(j.responsables||[]);}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar.")}},[id]);useEffect(()=>{cargar()},[cargar]);
async function actualizar(e:FormEvent<HTMLFormElement>){e.preventDefault();setGuardando(true);try{const f=new FormData(e.currentTarget),u=JSON.parse(localStorage.getItem("user")||"{}");const r=await fetch(`/api/bitacora/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json","x-user-codigo":u.codigo||""},body:JSON.stringify(Object.fromEntries(f.entries()))});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);await cargar()}catch(e){setError(e instanceof Error?e.message:"No fue posible actualizar.")}finally{setGuardando(false)}}
async function comentar(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),u=JSON.parse(localStorage.getItem("user")||"{}");setGuardando(true);try{const r=await fetch(`/api/bitacora/${id}`,{method:"POST",headers:{"Content-Type":"application/json","x-user-codigo":u.codigo||""},body:JSON.stringify({contenido:f.get("contenido")})});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);form.reset();await cargar()}catch(e){setError(e instanceof Error?e.message:"No fue posible comentar.")}finally{setGuardando(false)}}
if(!hilo)return <p>{error||"Cargando registro..."}</p>;
return <main><Link href="/miembros/bitacora">← Volver a la bitácora</Link><p className="sobre">{hilo.tipo.replaceAll("_"," ")} · {hilo.modulo.replaceAll("_"," ")}</p><h1>{hilo.titulo}</h1><p className="descripcion">{hilo.descripcion}</p>{hilo.ruta&&(hilo.ruta.startsWith("/")?<Link href={hilo.ruta}>Abrir página relacionada: {hilo.ruta}</Link>:<p>Referencia: {hilo.ruta}</p>)}<p className="meta">Creado por {hilo.creador?.nombre} el {new Date(hilo.created_at).toLocaleString("es-GT")} · Última actividad: {new Date(hilo.updated_at).toLocaleString("es-GT")}</p>
<form className="control" onSubmit={actualizar}><label>Estado<select name="estado" defaultValue={hilo.estado} key={`e${hilo.updated_at}`}>{["PENDIENTE","EN_ANALISIS","APROBADA","EN_PROCESO","RESUELTA","DESCARTADA"].map(x=><option key={x}>{x}</option>)}</select></label><label>Prioridad<select name="prioridad" defaultValue={hilo.prioridad} key={`p${hilo.updated_at}`}>{["BAJA","MEDIA","ALTA","URGENTE"].map(x=><option key={x}>{x}</option>)}</select></label><label>Responsable<select name="responsable_id" defaultValue={hilo.responsable_id||""} key={`r${hilo.updated_at}`}><option value="">Sin asignar</option>{responsables.map(r=><option key={r.id} value={r.id}>{r.nombre}</option>)}</select></label><button disabled={guardando}>Guardar seguimiento</button></form>{error&&<p className="error">{error}</p>}
<h2>Conversación e historial</h2><section className="comentarios">{comentarios.length===0&&<p>Aún no hay intervenciones.</p>}{comentarios.map(c=><article key={c.id} className={c.tipo==="COMENTARIO"?"":"evento"}><strong>{c.autor?.nombre||"Miembro"}</strong><small>{new Date(c.created_at).toLocaleString("es-GT")}</small><p>{c.contenido}</p>{c.tipo!=="COMENTARIO"&&<span>{c.tipo.replaceAll("_"," ")}</span>}</article>)}</section><form className="nuevo" onSubmit={comentar}><label>Agregar comentario<textarea name="contenido" required minLength={2} rows={5}/></label><button disabled={guardando}>Publicar comentario</button></form>
<style jsx>{`main{max-width:920px;overflow-wrap:anywhere}.sobre{margin-top:1.7rem;color:#6b6f1a;font-weight:700}.descripcion{font-size:1.08rem;line-height:1.8;white-space:pre-wrap}.meta{color:#666;font-size:.9rem}.control{display:grid;grid-template-columns:repeat(3,1fr) auto;gap:.75rem;align-items:end;background:#faf8f3;border:1px solid #ddd4c7;padding:1rem;border-radius:12px;margin:1.5rem 0}label{display:grid;gap:.3rem;font-weight:700}select,textarea{width:100%;box-sizing:border-box;padding:.7rem;border:1px solid #cfc5b7;border-radius:7px;font:inherit}button{background:#6b6f1a;color:white;border:0;padding:.75rem 1rem;border-radius:8px;font-weight:700}.comentarios{display:grid;gap:.8rem}.comentarios article{border:1px solid #ddd4c7;border-radius:10px;padding:1rem;background:white}.comentarios small{display:block;color:#777;margin-top:.2rem}.comentarios p{white-space:pre-wrap;line-height:1.7}.comentarios .evento{background:#f7f5ef}.comentarios span{font-size:.72rem;color:#6b6f1a;font-weight:700}.nuevo{display:grid;gap:.7rem;margin-top:1.2rem}.nuevo button{justify-self:start}.error{color:#8a2020}@media(max-width:760px){.control{grid-template-columns:1fr}.control button{justify-self:start}}`}</style></main>}