export const TEMAS_TRABAJOS_INV: Record<string, string[]> = {
  "unidad-1": [
    "La diferencia entre describir e interpretar una pieza numismática",
    "El objeto numismático como fuente primaria material",
    "De la curiosidad personal a una pregunta de investigación delimitada",
    "Los riesgos del anacronismo en la investigación numismática",
    "La formulación de hipótesis a partir de una pieza o serie monetaria",
    "La procedencia de una pieza como parte de su valor documental",
    "Observación, descripción e interpretación de una moneda o billete",
    "Cómo convertir una anomalía numismática en una pregunta investigable",
    "Los límites de la evidencia visual en el estudio de una pieza",
    "Errores frecuentes al investigar a partir de objetos sin contexto",
  ],
  "unidad-2": [
    "La construcción de un corpus adecuado para una investigación numismática",
    "El valor y los límites de los catálogos como fuentes de investigación",
    "Fuentes normativas y oficiales para reconstruir una emisión monetaria",
    "La búsqueda archivística para recuperar el contexto de una pieza",
    "La importancia de documentar y hacer reproducible una búsqueda de fuentes",
    "La prensa histórica como fuente para estudiar circulación y recepción monetaria",
    "Repositorios digitales y criterios para evaluar sus documentos",
    "Diferencias entre bibliografía de referencia y corpus de investigación",
    "La procedencia y cadena de custodia de imágenes numismáticas",
    "Estrategias para investigar cuando las fuentes principales no están disponibles",
  ],
  "unidad-3": [
    "Autoría, contexto y propósito en la evaluación de una fuente numismática",
    "Fuentes primarias y secundarias como categorías relativas a la pregunta",
    "La dependencia entre fuentes y la falsa apariencia de consenso",
    "Cómo tratar contradicciones entre fuentes numismáticas",
    "Grados de confianza y límites de una afirmación histórica",
    "Intereses institucionales y sesgos en documentos monetarios oficiales",
    "La proximidad temporal como criterio para evaluar una fuente",
    "El testimonio oral como fuente para la historia numismática reciente",
    "Errores de atribución que se reproducen entre catálogos",
    "Criterios para verificar la autenticidad y procedencia de una imagen",
  ],
  "unidad-4": [
    "Diferencias metodológicas entre identificar, clasificar y catalogar",
    "El uso de criterios explícitos para distinguir tipos y variantes",
    "La descripción sistemática como fundamento de la clasificación",
    "Los límites de un catálogo frente a piezas que no encajan en sus categorías",
    "Propuesta razonada de clasificación para un conjunto numismático delimitado",
    "Tipo, variante y subvariante como niveles de clasificación",
    "Mediciones y atributos materiales en la descripción sistemática",
    "Cómo registrar piezas dudosas o incompletas dentro de una clasificación",
    "Comparación crítica entre dos sistemas de catalogación",
    "Ventajas y riesgos de los catálogos numismáticos digitales",
  ],
  "unidad-5": [
    "La diferencia entre legislación monetaria y circulación efectiva",
    "El cono monetario como herramienta para reconstruir un sistema",
    "Evidencias para estudiar una transición entre sistemas monetarios",
    "La reforma decimal guatemalteca de 1870–1871 como problema histórico",
    "Reconstrucción de un episodio monetario mediante fuentes de distinta naturaleza",
    "Coexistencia de monedas nacionales y extranjeras en un periodo histórico",
    "La distancia entre una reforma legal y su aplicación efectiva",
    "Cambios de denominación y permanencias dentro de un sistema monetario",
    "Tipos de cambio y equivalencias como evidencia de transición monetaria",
    "Ausencias y discontinuidades en la reconstrucción de un cono monetario",
  ],
  "unidad-6": [
    "La exonumia como fuente para reconstruir relaciones económicas y sociales",
    "Criterios para distinguir una ficha particular de una moneda",
    "Las fichas de finca y la necesidad de interpretar su contexto de uso",
    "Fuentes documentales para investigar una pieza exonúmica",
    "Propuesta de identificación y clasificación de un conjunto exonúmico",
    "Diversidad de funciones de las fichas particulares guatemaltecas",
    "Atribución de una ficha a su emisor mediante evidencia documental",
    "Fichas, trabajo y relaciones económicas en una comunidad determinada",
    "Alcances y límites de la expresión ficha de finca",
    "Vacíos documentales y cautela interpretativa en el estudio de la exonumia",
  ],
  "unidad-7": [
    "El billete como documento institucional, material e histórico",
    "Textos e imágenes del papel moneda como evidencia de su época",
    "El inicio del papel moneda guatemalteco en 1874 y su contexto",
    "Los emisores como actores de la historia bancaria guatemalteca",
    "Interpretación de un billete mediante la pieza y fuentes externas",
    "La casa impresora como participante en el diseño del papel moneda",
    "Firmas, series y numeraciones como evidencia administrativa",
    "Elementos de seguridad y transformación tecnológica del billete",
    "Iconografía nacional y selección de personajes en una emisión",
    "Billetes conmemorativos entre documento histórico y objeto de colección",
  ],
  "unidad-8": [
    "Diferencias entre dato, evidencia, inferencia e interpretación",
    "Los riesgos de confundir correlación con causalidad en historia monetaria",
    "La comparación de explicaciones alternativas para un mismo fenómeno",
    "Cómo expresar incertidumbre sin debilitar una investigación",
    "Construcción de una explicación histórica sustentada en evidencia trazable",
    "Comparación de hipótesis rivales para explicar una emisión monetaria",
    "El uso prudente de evidencia negativa en una investigación",
    "Sesgos de selección producidos por colecciones y catálogos incompletos",
    "Causalidad, coincidencia temporal y explicación histórica",
    "Cómo revisar una interpretación cuando aparece evidencia contradictoria",
  ],
  "unidad-9": [
    "De la pregunta de investigación a una tesis defendible",
    "La relación entre tesis, argumentos y evidencia en un ensayo académico",
    "Integración y atribución correcta de fuentes dentro de la escritura académica",
    "La estructura del ensayo como expresión del razonamiento investigador",
    "La revisión crítica como parte del proceso de escritura",
    "Construcción de un esquema argumental antes de redactar",
    "Integración de citas sin perder la voz del autor",
    "Uso de imágenes, cuadros y catálogos como evidencia dentro del ensayo",
    "El contraargumento como recurso para fortalecer una tesis",
    "Reescritura académica a partir de observaciones fundamentadas",
  ],
  "unidad-10": [
    "Del interés personal a un problema de investigación viable",
    "Delimitación de la pregunta, el corpus y el alcance de una investigación",
    "Diseño metodológico para una investigación numismática o notafílica",
    "Viabilidad, trazabilidad y límites de una propuesta de investigación",
    "Formulación de una propuesta propia para continuar investigando después del nivel",
    "Plan de trabajo y viabilidad de una investigación numismática",
    "Acceso a fuentes y delimitación realista de un proyecto",
    "Aporte original y pertinencia académica de una investigación",
    "Consideraciones éticas en el uso de colecciones, imágenes y testimonios",
    "Limitaciones previsibles y resultados alcanzables de una propuesta",
  ],
};
