"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Hilo = { id:number;titulo:string;descripcion:string;tipo:string;modulo:string;prioridad:string;estado:string;updated_at:string;comentarios_count:number;creador?:{nombre:string};responsable?:{nombre:string}|null };
const etiqueta = (s:string) => s.replaceAll("_", " ");

export default function BitacoraPage() {
  const [hilos,setHilos]=useState<Hilo[]>([]), [buscar,setBuscar]=useState(""), [estado,setEstado]=useState(""), [tipo,setTipo]=useState(""), [prioridad,setPrioridad]=useState("");
  const [cargando,setCargando]=useState(true), [error,setError]=useState("");
  useEffect(()=>{(async()=>{try{const u=JSON.parse(localStorage.getItem("user")||"{}");const r=await fetch("/api/bitacora",{headers:{"x-user-codigo":u.codigo||""},cache:"no-store"});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error);setHilos(j.hilos||[]);}catch(e){setError(e instanceof Error?e.message:"No fue posible cargar la bitácora.");}finally{setCargando(false);}})()},[]);
  const filtrados=useMemo(()=>hilos.filter(h=>{const q=buscar.toLowerCase();return(!q||`${h.titulo} ${h.descripcion} ${h.modulo}`.toLowerCase().includes(q))&&(!estado||h.estado===estado)&&(!tipo||h.tipo===tipo)&&(!prioridad||h.prioridad===prioridad)}),[hilos,buscar,estado,tipo,prioridad]);
  if(cargando)return <p>Cargando bitácora...</p>;
  return <main className="bitacora"><div className="encabezado"><div><p className="sobre">CA · CE</p><h1>Bitácora interna</h1><p>Observaciones, mejoras, decisiones y seguimiento del funcionamiento de AGENN.</p></div><Link className="boton" href="/miembros/bitacora/nuevo">Nuevo registro</Link></div>
    {error&&<p className="error">{error}</p>}
    <section className="filtros"><input value={buscar} onChange={e=>setBuscar(e.target.value)} placeholder="Buscar por título, contenido o módulo..."/><select value={estado} onChange={e=>setEstado(e.target.value)}><option value="">Todos los estados</option>{["PENDIENTE","EN_ANALISIS","APROBADA","EN_PROCESO","RESUELTA","DESCARTADA"].map(x=><option key={x}>{x}</option>)}</select><select value={tipo} onChange={e=>setTipo(e.target.value)}><option value="">Todos los tipos</option>{["ERROR","MEJORA","CONTENIDO","DECISION","EDITORIAL","OTRO"].map(x=><option key={x}>{x}</option>)}</select><select value={prioridad} onChange={e=>setPrioridad(e.target.value)}><option value="">Toda prioridad</option>{["BAJA","MEDIA","ALTA","URGENTE"].map(x=><option key={x}>{x}</option>)}</select></section>
    <p>{filtrados.length} registro{filtrados.length===1?"":"s"}</p><section className="lista">{filtrados.map(h=><article key={h.id}><div className="badges"><span>{etiqueta(h.tipo)}</span><span>{etiqueta(h.estado)}</span><span className={h.prioridad}>{h.prioridad}</span></div><h2><Link href={`/miembros/bitacora/${h.id}`}>{h.titulo}</Link></h2><p>{h.descripcion.length>260?h.descripcion.slice(0,260)+"…":h.descripcion}</p><small>{h.modulo} · Creado por {h.creador?.nombre||"—"} · Responsable: {h.responsable?.nombre||"sin asignar"} · {h.comentarios_count} intervenciones · {new Date(h.updated_at).toLocaleDateString("es-GT")}</small></article>)}</section>
    <style jsx>{`.bitacora{max-width:1050px;overflow:hidden}.encabezado{display:flex;justify-content:space-between;gap:1rem;align-items:flex-start}.sobre{color:#6b6f1a;font-weight:700}.boton{background:#6b6f1a;color:white;padding:.8rem 1rem;border-radius:8px;text-decoration:none;font-weight:700;white-space:nowrap}.filtros{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:.7rem;margin:1.5rem 0}.filtros input,.filtros select{min-width:0;padding:.75rem;border:1px solid #cfc5b7;border-radius:8px}.lista{display:grid;gap:1rem}.lista article{background:#fff;border:1px solid #ddd4c7;border-radius:12px;padding:1.2rem;overflow-wrap:anywhere}.lista h2{margin:.55rem 0}.lista h2 a{color:#33250f}.badges{display:flex;gap:.45rem;flex-wrap:wrap}.badges span{font-size:.75rem;background:#eee9df;padding:.25rem .5rem;border-radius:99px}.badges .URGENTE{background:#f9dada;color:#8a2020}.badges .ALTA{background:#fff0c9}.error{color:#8a2020}@media(max-width:760px){.encabezado{display:block}.boton{display:inline-block;margin-top:.5rem}.filtros{grid-template-columns:1fr}.lista small{display:block;line-height:1.6}}`}</style></main>;
}